# Created with package:mono_repo v1.2.1
language: dart

jobs:
  include:
    - stage: analyzer_and_format
      name: "SDK: stable - DIR: packages/functional_widget - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="packages/functional_widget"
      dart: stable
    - stage: analyzer_and_format
      name: "SDK: stable - DIR: packages/functional_widget_generator - TASKS: [dartfmt -n --set-exit-if-changed ., dartanalyzer --fatal-infos --fatal-warnings .]"
      script: ./tool/travis.sh dartfmt dartanalyzer
      env: PKG="packages/functional_widget_generator"
      dart: stable
    - stage: unit_test
      name: "SDK: stable - DIR: packages/functional_widget_generator - TASKS: pub run test"
      script: ./tool/travis.sh test
      env: PKG="packages/functional_widget_generator"
      dart: stable

stages:
  - analyzer_and_format
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - packages/functional_widget/.dart_tool/build
    - packages/functional_widget_generator/.dart_tool/build
