name: functional_widget
description: A code generator that generates widget classes from their implementation as a function.
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/functional_widget/tree/master/functional_widget
version: 0.8.1
environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  analyzer: '>=0.39.5 <1.0.0'
  build: ">=0.12.6 <2.0.0"
  build_config: ">=0.4.2 <1.0.0"
  meta: ">=1.2.0 <2.0.0"
  functional_widget_annotation: ">=0.8.0 <2.0.0"
  source_gen: ^0.9.5
  code_builder: ^3.2.1

dev_dependencies:
  test: ^1.15.4
  mockito: ^4.1.1
  dart_style: ^1.3.6
  pedantic: ^1.9.0
  build_runner: ^1.10.3
  code_gen_tester:
    path: ./code_gen_tester
