name: functional_widget_annotation
description: Annotations for function_widget_generator used to generate widget classes from a function
homepage: https://github.com/rrousselGit/functional_widget/tree/master/packages/functional_widget_annotation
version: 0.9.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
