name: functional_widget_annotation_example
description: A new Flutter project.
environment:
  sdk: ^2.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.0.0

dependency_overrides:
  functional_widget_annotation:
    path: ../
  functional_widget:
    path: ../../functional_widget
