name: functional_widget_generator
description: work in progress
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/functional_widget
version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  functional_widget: 0.0.1
  source_gen: ^0.9.1+3
  build_config: ^0.3.1+4
  code_builder: ^3.1.3
  build: ^1.0.1
  analyzer: ^0.34.0

dev_dependencies:
  test: 1.5.1+1
  mockito: 4.0.0
  dart_style: 1.2.0